### ISSUE TITLE
Cannot build: `objcopy: BOOTX64.so: Invalid bfd target`

### ISSUE THREAD

**Issue by jepio** [yasuoka/openbsd-uefi#1]
So I'm trying to build the efi bootloader on OpenBSD 5.7 but I'm hitting this error

```
===> bootx64
objcopy -j .text -j .sdata -j .data -j .dynamic -j .dynsym -j .rel  -j .rel.* -j .rela -j .rela.* -j .reloc  --target=efi-app-x86_64 BOOTX64.so BOOTX64.EFI
objcopy: BOOTX64.so: Invalid bfd target
*** Error 1 in bootx64 (../Makefile.common:63 'BOOTX64.EFI')
*** Error 1 in /usr/src/openbsd-uefi/src/sys/arch/amd64/stand/efiboot (<bsd.subdir.mk>:48 'all')
```

Indeed objcopy doesn't support this target

```
$ objcopy -h
[...]
objcopy: supported targets: elf64-x86-64 elf32-i386 coff-i386 efi-app-ia32 elf64-little elf64-big elf32-little elf32-big srec symbolsrec tekhex binary ihex netbsd-core
```

How do you get this to build? Have the targets been changed in OpenBSD-current? 
I've been trying to build binutils with this target manually but I haven't been successful.

**Comment by yasuoka** [comment]
binutils is upgraded on 5.7 => 5.8.  Build seems to require the latest objcopy on OpenBSD.

**Comment by jepio** [comment]
Yes I see, indeed after upgrading to 5.8 I can build it and boot the EFI
boot loader successfully (in a vm for now, about to try on real hardware).

Is there any location where I could place the boot configuration file for
use with the EFI boot loader?

On Sat, Aug 29, 2015 at 11:53 PM, YASUOKA Masahiko <notifications@github.com

**Comment by yasuoka** [comment]
it tries to read /etc/boot.conf on the openbsd partion of the first disk.
order of the disk can be determined by

```
probing: hd0 hd1*
```

line.  disks without \* have a OpenBSD parition, and "machine disk" will also help.
