### ISSUE TITLE
Cannot find files/partitions on drive after boot

### ISSUE THREAD

**Issue by b1twise** [yasuoka/openbsd-uefi#2]
I'm testing on a Macbook 2015.  I've tried from both an external USB drive as well as my own EFI partition on the laptop.  It only has the EFI partition on the internal disk, created by OSX running on a USB flash drive.

I'm using the snapshot from ftp.openbsd.org/pub/OpenBSD/snapshots/amd64, both the bootx and bsd.sd.  Ihad trouble objcopy as noted, so I was going for a fresh install when I found the snapshot files.

When booted from external USB, the boot strings find hd0 and hd1--which maps logically to me to the USB drive and internal drive.  The default drive is fd0a.  fd0a doesn't seem to function with ls. I'm having a similar problem with the drives.  I'm not sure what to call them.  hd0, sd0, wd0, hd0a....?

The same holds true for a boot using only the internal disk.  Only hd0 found on boot, defaults to fd0a, can't find bsd to push forward.

Anything I can do, i will try.

**Comment by yasuoka** [comment]
ls command will work only against a BSD partition (for this moment, at least).  "ls hd1a:/" for example.
The disk has an OpenBSD disklabel and BSD partition?  Both of them are required.

Also, check the "probing: " line from the loader

```
probing: hd0* hd1
```

If you can find hd? without *, that means the boot loader found the
openbsd disklabel.

**Comment by b1twise** [comment]
- Yesterday I was able to get a successful boot into UEFI on a 2015
  MacBook.  I haven't figured out how to put both EFI partition and a
  BSD partition for the bsd files onto a single USB stick yet.  I spent
  time on that--which delayed my response.
- The MacBook seems to demand EFI support--dropping non-EFI boot from
  even USB.  I also have a 2014 or 2013 MacBook Air that only allows
  compat mode on one boot (for OS install).

I'll send results from the MBA and a 2012 MBPr soon.

I am so appreciative of the work you're doing on this.  It's one step
closer to OBSD on Apple hardware.  The kernel boots on the MBA and
MacBook, but no recognition of keyboard and mouse unless its's a compat
boot on the MBA.

Anyway, take care.  If there's anything I can do to help or test, let me
know.  I really appreciate the effort.

--Joel

**Comment by yasuoka** [comment]
Nice progress!  I'm looking forward to your diff for macbook.

**Comment by gonzalo-** [comment]
Hi!
My Setup is a Macbookpro12,1 I buy one of those sd with 128gb on it to install OpenBSD. I do the EFI partition on osx, put the BOOTX64.EFI on EFI/BOOT/ and then with VirtualBox install OpenBSD on the rest of the SD as usual, then reboot osx holding 'alt', go to EFI, and UEFI Bootloader found only hd0\* and hd1\* but can't boot from any.

UPDATE: With a today (25 sep) install58.fs on a usb stick I got this now:

![img_1788](https://cloud.githubusercontent.com/assets/3194502/10109740/41764c94-639f-11e5-88a2-35c6c0d575f6.JPG)

Freeze there, then reboots

Any ideas?

**Comment by yasuoka** [comment]
On hd1, the efiboot seems to have found an OpenBSD parition.
Failing at loading the kernel seems to be the same problem of
http://marc.info/?l=openbsd-misc&m=144254099606540&w=2 .  That bug is what I am currently fixing.

**Comment by gonzalo-** [comment]
The partition is the usb, and that is what freeze!

I wAit for the fix! Thanks!

**Comment by yasuoka** [comment]
Committed an important fix on openbsd's cvs.

**Comment by gonzalo-** [comment]
Awesome, I'm gonna build the files and try it in a few days, of you already have it, link is welcome :)

Thanks!

**Comment by yasuoka** [comment]
The fix is included latest snapshot.  You can get it from http://ftp.openbsd.org/pub/OpenBSD/snapshots/amd64/

**Comment by gonzalo-** [comment]
I have the same problem, booting from install58.fs from usb stick or with BOOTX64.EFI from SD:

![img_1847](https://cloud.githubusercontent.com/assets/3194502/10319325/178454f0-6c44-11e5-8db9-57f905222ac7.JPG)

Stay there for a sec and then freeze or reboots

**Comment by yasuoka** [comment]
As the result of Joerg Jung and Bryan Vyhmeist helps, almost all problems are getting to be fixed.

I think you can boot the OpenBSD installer by
- Use latest snapshot's install58.fs
- boot hd0a:5.8/amd64/bsd.rd (not /bsd)

I'd like you to try this.

**Comment by gonzalo-** [comment]
AWESOME!!!!!

I just test that, and go to installation just fine!

I'm gonna install this tonight or tomorrow, thank you so much!

**Comment by gonzalo-** [comment]
Well, I can install just fine OpenBSD with this, but now I need to figure out why OSX doesn't see the disk to boot! xD

But that is another history! Thanks!

**Comment by yasuoka** [comment]
The remaining issue of loading hd0a:/bsd was that UEFI interrupt
destroys the zlib stack since efiboot is compiled without
-mno-red-zone.  It is the same issue of
https://bugs.launchpad.net/ubuntu/+source/efilinux/+bug/1025931

I fixed this on cvs.  Thank you for your report!
